from dsg_spatialqa_lab.adapters import (
    AI2THOR_MISSING_DEPENDENCY_MESSAGE,
    AI2ThorAdapterConfig,
    AI2ThorEpisodeCollector,
    HABITAT_MISSING_DEPENDENCY_MESSAGE as HABITAT_MISSING_DEPENDENCY_MESSAGE,
    HabitatAdapterConfig as HabitatAdapterConfig,
    HabitatEpisodeCollector as HabitatEpisodeCollector,
    build_mock_ai2thor_episode,
    build_mock_habitat_episode as build_mock_habitat_episode,
    convert_ai2thor_event_to_episode_frame,
    convert_habitat_observation_to_episode_frame as convert_habitat_observation_to_episode_frame,
)
from dsg_spatialqa_lab.agents import (
    ActiveGraphAgent as ActiveGraphAgent,
    ActiveTaskResult as ActiveTaskResult,
    BaselineAgent,
    BaselineSpec,
    CaptionMemoryBaselineAgent,
    GraphTextBaselineAgent,
    GraphToolBaselineAgent,
    MajorityBaselineAgent,
    baseline_spec_to_dict,
    get_baseline_agent,
    list_active_policies as list_active_policies,
    list_baselines,
    run_active_task_policy as run_active_task_policy,
    run_baseline_predictions,
)
from dsg_spatialqa_lab.benchmark import (
    BENCHMARK_MANIFEST_SCHEMA_VERSION as BENCHMARK_MANIFEST_SCHEMA_VERSION,
    QACase,
    benchmark_manifest_digest as benchmark_manifest_digest,
    benchmark_manifest_json as benchmark_manifest_json,
    build_benchmark_artifacts as build_benchmark_artifacts,
    compare_benchmark_manifest as compare_benchmark_manifest,
    compare_qa_dataset,
    generate_qa_cases,
    load_benchmark_manifest as load_benchmark_manifest,
    load_qa_dataset,
    qa_case_from_dict,
    qa_case_to_dict,
    qa_dataset_digest,
    qa_dataset_jsonl,
    qa_dataset_summary,
    save_benchmark_manifest as save_benchmark_manifest,
    save_qa_dataset,
    validate_benchmark_manifest as validate_benchmark_manifest,
    validate_qa_dataset,
)
from dsg_spatialqa_lab.evaluation import (
    EvaluationCase,
    SceneLoader,
    compare_evaluation_bundle,
    compare_evaluation_case_listing,
    compare_evaluation_manifest,
    compare_evaluation_report,
    evaluation_bundle,
    evaluation_bundle_digest,
    evaluation_bundle_json,
    evaluation_case_listing,
    evaluation_case_listing_digest,
    evaluation_case_listing_json,
    evaluation_case_metadata,
    evaluation_manifest,
    evaluation_manifest_digest,
    evaluation_manifest_json,
    evaluation_report,
    evaluation_report_digest,
    evaluation_report_json,
    evaluation_cases_metadata,
    get_evaluation_case,
    list_evaluation_case_metadata,
    list_evaluation_cases,
    load_evaluation_bundle,
    load_evaluation_case_listing,
    load_evaluation_manifest,
    load_evaluation_report,
    run_evaluation_case,
    run_evaluation_case_definition,
    run_evaluation_cases,
    run_evaluation_suite,
    save_evaluation_bundle,
    save_evaluation_case_listing,
    save_evaluation_manifest,
    save_evaluation_report,
    validate_evaluation_bundle,
    validate_evaluation_case_listing,
    validate_evaluation_manifest,
    validate_evaluation_report,
)
from dsg_spatialqa_lab.eval import (
    OfflinePredictionRecord,
    QAPrediction,
    active_task_report as active_task_report,
    active_task_report_digest as active_task_report_digest,
    active_task_report_json as active_task_report_json,
    active_task_result_from_dict as active_task_result_from_dict,
    active_task_result_to_dict as active_task_result_to_dict,
    active_task_results_digest as active_task_results_digest,
    active_task_results_jsonl as active_task_results_jsonl,
    attribute_qa_errors,
    compare_error_attribution_report,
    compare_graph_eval_report,
    compare_offline_prediction_import_report,
    compare_graphs,
    compare_qa_eval_report,
    error_attribution_report,
    error_attribution_report_digest,
    error_attribution_report_json,
    evaluate_qa_predictions,
    graph_eval_report,
    graph_eval_report_digest,
    graph_eval_report_json,
    import_offline_predictions,
    load_active_task_report as load_active_task_report,
    load_error_attribution_report,
    load_graph_eval_report,
    load_offline_prediction_import_report,
    load_offline_prediction_records,
    load_qa_eval_report,
    load_qa_predictions,
    offline_prediction_import_report_digest,
    offline_prediction_import_report_json,
    offline_prediction_record_from_dict,
    offline_prediction_record_to_dict,
    offline_prediction_records_digest,
    offline_prediction_records_from_jsonl,
    offline_prediction_records_jsonl,
    qa_eval_report,
    qa_eval_report_digest,
    qa_eval_report_json,
    qa_prediction_from_dict,
    qa_prediction_to_dict,
    qa_predictions_digest,
    qa_predictions_jsonl,
    save_active_task_report as save_active_task_report,
    save_error_attribution_report,
    save_graph_eval_report,
    save_offline_prediction_import_report,
    save_offline_prediction_records,
    save_qa_eval_report,
    save_qa_predictions,
    validate_graph_eval_report,
    validate_active_task_report as validate_active_task_report,
    validate_error_attribution_report,
    validate_offline_prediction_import_report,
    validate_qa_eval_report,
)
from dsg_spatialqa_lab.episodes import (
    EpisodeAction,
    EpisodeFrame,
    EpisodeMetadata,
    EpisodeRecord,
    EpisodeSequence,
    compare_episode_sequence,
    episode_frame_from_dict,
    episode_frame_to_dict,
    episode_sequence_digest,
    episode_sequence_from_jsonl,
    episode_sequence_summary,
    episode_sequence_to_jsonl,
    load_episode_sequence,
    save_episode_sequence,
    validate_episode_sequence,
)
from dsg_spatialqa_lab.graph_tool import GraphTool
from dsg_spatialqa_lab.memory import DynamicSceneGraph
from dsg_spatialqa_lab.observations import (
    IngestResult,
    NodeObservation,
    ObjectObservation,
    ObservationIngestor,
    SceneObservation,
    compare_scene_observation_sequence_summary,
    compare_observation_ingest_report,
    ingest_scene_observation_sequence,
    load_observation_ingest_report,
    load_scene_observation,
    load_scene_observation_sequence,
    load_scene_observation_sequence_summary,
    observation_ingest_report,
    observation_ingest_report_digest,
    observation_ingest_report_json,
    save_observation_ingest_report,
    save_scene_observation,
    save_scene_observation_sequence,
    save_scene_observation_sequence_summary,
    scene_observation_from_dict,
    scene_observation_from_json,
    scene_observation_sequence_from_dict,
    scene_observation_sequence_from_json,
    scene_observation_sequence_digest,
    scene_observation_sequence_summary,
    scene_observation_sequence_summary_digest,
    scene_observation_sequence_summary_json,
    scene_observation_sequence_to_dict,
    scene_observation_sequence_to_json,
    scene_observation_to_dict,
    scene_observation_to_json,
    validate_scene_observation_sequence_payload,
    validate_scene_observation_sequence_summary,
    validate_observation_ingest_report,
)
from dsg_spatialqa_lab.oracle import (
    OracleObjectRecord,
    build_oracle_graph_from_episode,
    compare_oracle_graph_report,
    load_oracle_graph_report,
    oracle_graph_report,
    oracle_graph_report_digest,
    oracle_graph_report_json,
    oracle_graph_summary,
    save_oracle_graph_report,
    validate_oracle_graph_report,
)
from dsg_spatialqa_lab.perception import (
    Detection2D,
    Instance3D,
    MockDepthProjector,
    MockSegmenter,
    SimpleObjectFusion,
    SimpleObjectTracker,
)
from dsg_spatialqa_lab.predicted import (
    build_predicted_graph_from_episode,
    compare_predicted_graph_report,
    load_predicted_graph_report,
    predicted_graph_report,
    predicted_graph_report_digest,
    predicted_graph_report_json,
    predicted_graph_summary,
    save_predicted_graph_report,
    validate_predicted_graph_report,
)
from dsg_spatialqa_lab.qa import SpatialQAEngine
from dsg_spatialqa_lab.relations import RelationConfig, RelationEngine
from dsg_spatialqa_lab.scene_io import (
    compare_graph_file_to_fixture,
    compare_graph_report,
    compare_graph_report_to_file,
    compare_graph_to_fixture,
    graph_from_dict,
    graph_from_json,
    graph_json_digest,
    graph_report,
    graph_report_digest,
    graph_report_json,
    graph_summary,
    graph_to_dict,
    graph_to_json,
    load_graph_report,
    load_graph_json,
    save_graph_report,
    save_graph_json,
    validate_graph_report,
)
from dsg_spatialqa_lab.scenes import (
    SceneFixture,
    build_ambiguous_mugs_scene,
    build_ambiguous_plates_scene,
    build_moved_mug_scene,
    build_multi_room_rearrangement_scene,
    build_needs_reobserve_scene,
    build_relation_shift_scene,
    build_tabletop_scene,
    compare_scene_fixture_manifest,
    get_scene_fixture,
    list_scene_fixture_metadata,
    list_scene_fixtures,
    load_scene_fixture_manifest,
    load_scene_fixture,
    save_scene_fixture_manifest,
    scene_fixture_manifest,
    scene_fixture_manifest_json,
    validate_scene_fixture_manifest,
)
from dsg_spatialqa_lab.schema import (
    ActionValidation,
    AgentPoseState,
    BBox3D,
    Edge,
    GraphQuery,
    Node,
    ObjectState,
    PlannerResult,
    Pose3D,
    QAResponse,
    SkillCommand,
    SpatialQAError,
    Subgraph,
)
from dsg_spatialqa_lab.tasks import (
    ActiveAction as ActiveAction,
    ActiveEQATask as ActiveEQATask,
    ActiveObservation as ActiveObservation,
    MockActiveEnvironment as MockActiveEnvironment,
    active_eqa_task_from_dict as active_eqa_task_from_dict,
    active_eqa_task_to_dict as active_eqa_task_to_dict,
    active_eqa_tasks_digest as active_eqa_tasks_digest,
    active_eqa_tasks_from_jsonl as active_eqa_tasks_from_jsonl,
    active_eqa_tasks_jsonl as active_eqa_tasks_jsonl,
    load_active_eqa_tasks as load_active_eqa_tasks,
    save_active_eqa_tasks as save_active_eqa_tasks,
    validate_active_eqa_tasks as validate_active_eqa_tasks,
)
from dsg_spatialqa_lab.vla import VLAAnchorPlanner
from dsg_spatialqa_lab.visualization import (
    dashboard_bundle,
    dashboard_bundle_digest,
    dashboard_bundle_json,
    dashboard_html,
    export_dashboard,
    load_dashboard_bundle,
    save_dashboard_bundle,
    validate_dashboard_bundle,
)

__all__ = [
    "ActionValidation",
    "AI2THOR_MISSING_DEPENDENCY_MESSAGE",
    "AI2ThorAdapterConfig",
    "AI2ThorEpisodeCollector",
    "AgentPoseState",
    "BBox3D",
    "BaselineAgent",
    "BaselineSpec",
    "CaptionMemoryBaselineAgent",
    "Detection2D",
    "DynamicSceneGraph",
    "Edge",
    "EpisodeAction",
    "EpisodeFrame",
    "EpisodeMetadata",
    "EpisodeRecord",
    "EpisodeSequence",
    "EvaluationCase",
    "GraphTool",
    "GraphQuery",
    "IngestResult",
    "Instance3D",
    "GraphTextBaselineAgent",
    "GraphToolBaselineAgent",
    "MajorityBaselineAgent",
    "MockDepthProjector",
    "MockSegmenter",
    "Node",
    "NodeObservation",
    "ObjectState",
    "ObjectObservation",
    "ObservationIngestor",
    "OracleObjectRecord",
    "PlannerResult",
    "Pose3D",
    "QACase",
    "QAPrediction",
    "OfflinePredictionRecord",
    "QAResponse",
    "RelationConfig",
    "RelationEngine",
    "SimpleObjectFusion",
    "SimpleObjectTracker",
    "SkillCommand",
    "SpatialQAEngine",
    "SpatialQAError",
    "Subgraph",
    "SceneObservation",
    "attribute_qa_errors",
    "baseline_spec_to_dict",
    "compare_error_attribution_report",
    "compare_scene_observation_sequence_summary",
    "compare_observation_ingest_report",
    "compare_oracle_graph_report",
    "compare_predicted_graph_report",
    "compare_episode_sequence",
    "compare_offline_prediction_import_report",
    "compare_qa_eval_report",
    "compare_qa_dataset",
    "build_oracle_graph_from_episode",
    "build_predicted_graph_from_episode",
    "build_mock_ai2thor_episode",
    "convert_ai2thor_event_to_episode_frame",
    "dashboard_bundle",
    "dashboard_bundle_digest",
    "dashboard_bundle_json",
    "dashboard_html",
    "ingest_scene_observation_sequence",
    "load_observation_ingest_report",
    "load_oracle_graph_report",
    "load_predicted_graph_report",
    "load_scene_observation",
    "load_scene_observation_sequence",
    "load_scene_observation_sequence_summary",
    "load_episode_sequence",
    "observation_ingest_report",
    "observation_ingest_report_digest",
    "observation_ingest_report_json",
    "oracle_graph_report",
    "oracle_graph_report_digest",
    "oracle_graph_report_json",
    "oracle_graph_summary",
    "predicted_graph_report",
    "predicted_graph_report_digest",
    "predicted_graph_report_json",
    "predicted_graph_summary",
    "qa_case_from_dict",
    "qa_case_to_dict",
    "qa_dataset_digest",
    "qa_dataset_jsonl",
    "qa_dataset_summary",
    "qa_eval_report",
    "qa_eval_report_digest",
    "qa_eval_report_json",
    "qa_prediction_from_dict",
    "qa_prediction_to_dict",
    "qa_predictions_digest",
    "qa_predictions_jsonl",
    "save_observation_ingest_report",
    "save_oracle_graph_report",
    "save_predicted_graph_report",
    "save_qa_dataset",
    "save_qa_eval_report",
    "save_qa_predictions",
    "save_scene_observation",
    "save_scene_observation_sequence",
    "save_scene_observation_sequence_summary",
    "save_episode_sequence",
    "episode_frame_from_dict",
    "episode_frame_to_dict",
    "episode_sequence_digest",
    "episode_sequence_from_jsonl",
    "episode_sequence_summary",
    "episode_sequence_to_jsonl",
    "scene_observation_from_dict",
    "scene_observation_from_json",
    "scene_observation_sequence_from_dict",
    "scene_observation_sequence_from_json",
    "scene_observation_sequence_digest",
    "scene_observation_sequence_summary",
    "scene_observation_sequence_summary_digest",
    "scene_observation_sequence_summary_json",
    "scene_observation_sequence_to_dict",
    "scene_observation_sequence_to_json",
    "scene_observation_to_dict",
    "scene_observation_to_json",
    "validate_scene_observation_sequence_payload",
    "validate_scene_observation_sequence_summary",
    "validate_observation_ingest_report",
    "validate_oracle_graph_report",
    "validate_predicted_graph_report",
    "validate_qa_dataset",
    "validate_qa_eval_report",
    "validate_episode_sequence",
    "VLAAnchorPlanner",
    "SceneFixture",
    "SceneLoader",
    "build_ambiguous_mugs_scene",
    "build_ambiguous_plates_scene",
    "build_moved_mug_scene",
    "build_multi_room_rearrangement_scene",
    "build_needs_reobserve_scene",
    "build_relation_shift_scene",
    "build_tabletop_scene",
    "compare_scene_fixture_manifest",
    "compare_evaluation_bundle",
    "compare_evaluation_case_listing",
    "compare_evaluation_manifest",
    "compare_evaluation_report",
    "compare_graph_eval_report",
    "compare_graph_file_to_fixture",
    "compare_graph_report",
    "compare_graph_report_to_file",
    "compare_graph_to_fixture",
    "compare_graphs",
    "evaluation_bundle",
    "evaluation_bundle_digest",
    "evaluation_bundle_json",
    "evaluation_case_listing",
    "evaluation_case_listing_digest",
    "evaluation_case_listing_json",
    "evaluation_case_metadata",
    "evaluation_manifest",
    "evaluation_manifest_digest",
    "evaluation_manifest_json",
    "evaluation_report",
    "evaluation_report_digest",
    "evaluation_report_json",
    "evaluation_cases_metadata",
    "export_dashboard",
    "get_baseline_agent",
    "get_evaluation_case",
    "get_scene_fixture",
    "generate_qa_cases",
    "evaluate_qa_predictions",
    "error_attribution_report",
    "error_attribution_report_digest",
    "error_attribution_report_json",
    "graph_from_dict",
    "graph_from_json",
    "graph_json_digest",
    "graph_report",
    "graph_report_digest",
    "graph_report_json",
    "graph_summary",
    "graph_to_dict",
    "graph_to_json",
    "graph_eval_report",
    "graph_eval_report_digest",
    "graph_eval_report_json",
    "import_offline_predictions",
    "load_graph_report",
    "load_error_attribution_report",
    "load_graph_eval_report",
    "load_offline_prediction_import_report",
    "load_offline_prediction_records",
    "load_graph_json",
    "load_qa_dataset",
    "load_qa_eval_report",
    "load_qa_predictions",
    "offline_prediction_import_report_digest",
    "offline_prediction_import_report_json",
    "offline_prediction_record_from_dict",
    "offline_prediction_record_to_dict",
    "offline_prediction_records_digest",
    "offline_prediction_records_from_jsonl",
    "offline_prediction_records_jsonl",
    "list_baselines",
    "list_scene_fixture_metadata",
    "list_scene_fixtures",
    "list_evaluation_case_metadata",
    "list_evaluation_cases",
    "load_dashboard_bundle",
    "load_scene_fixture_manifest",
    "load_scene_fixture",
    "save_scene_fixture_manifest",
    "scene_fixture_manifest",
    "scene_fixture_manifest_json",
    "validate_scene_fixture_manifest",
    "load_evaluation_bundle",
    "load_evaluation_case_listing",
    "load_evaluation_manifest",
    "load_evaluation_report",
    "run_evaluation_case",
    "run_evaluation_case_definition",
    "run_evaluation_cases",
    "run_evaluation_suite",
    "run_baseline_predictions",
    "save_graph_report",
    "save_error_attribution_report",
    "save_dashboard_bundle",
    "save_graph_eval_report",
    "save_offline_prediction_import_report",
    "save_offline_prediction_records",
    "save_graph_json",
    "validate_graph_eval_report",
    "validate_offline_prediction_import_report",
    "validate_error_attribution_report",
    "validate_dashboard_bundle",
    "validate_graph_report",
    "save_evaluation_bundle",
    "save_evaluation_case_listing",
    "save_evaluation_manifest",
    "save_evaluation_report",
    "validate_evaluation_bundle",
    "validate_evaluation_case_listing",
    "validate_evaluation_manifest",
    "validate_evaluation_report",
]
